### ISSUE TITLE
Persistent top_view configuration

### ISSUE THREAD

**Issue by cnuke** [alex-ab/genode#1]
By now I use a specific configuration when I use `top_view` as debugging aid. It would be nice to be able to make some settings persistent, e.g., number of displayed threads per core, so that I do not have to fiddle around everytime I start `top_view`.

**Comment by alex-ab** [comment]
I added a [first version](https://github.com/alex-ab/genode/commits/sculpt_pkg_top_view_20_02) and published for Sculpt 20.02 in my experimental section two packages. The one is configured to report the config whenever the view is updated, should look like:

```
[init -> report_rom] report 'top_view -> config'
[init -> report_rom]   <config report="true" store="false" log="false" period_ms="9000" trace_ms="3000" view="list" list="components">
[init -> report_rom]   	<cpu xpos="0" ypos="0" show="true" threads="3"/>
[init -> report_rom]   	<cpu xpos="1" ypos="0" show="true" threads="4"/>
[init -> report_rom]   	<cpu xpos="2" ypos="0" show="false" threads="5"/>
[init -> report_rom]   	<cpu xpos="3" ypos="0" show="true" threads="6"/>
[init -> report_rom]   </config>
```
This report can then be used to configure the top_view component (so not the package in a launcher so to say). That meas you have to change the top_view package by hand manually and add this config to the corresponding ```<start name="top_view"``` node. If you can give it a test I would be grateful.

**Comment by alex-ab** [comment]
@cnuke: i added another package top_view_config/20-04-29 in my depot, see experimental section of alex-ab menu. The package now uses the recall fs, to read/write the config. In your recall fs you will need to provide a file /rw/recall/top_view_config/recall/config. The initial config as starting point you find in the pkg outcommented. Please try out.

**Comment by cnuke** [comment]
Thanks for implementing the feature, much appreciated - I'll give it a try.

**Comment by alex-ab** [comment]
Tested by @cnuke and me, available as ready to use package (top_view_config) via Sculpt OS, git repo: https://github.com/alex-ab/genode/commits/sculpt_pkg_top_view_20_08.
